[package]
name = "mdbook-wikilink"
version = "0.2.0"
authors = ["Victor Freire <victor@freire.dev.br>", "Leo Silva Souza <leovano@protonmail.com>", "Knut Magnus Aasrud <km@aasrud.com>"]
edition = "2018"

[dependencies]
clap = "*"
mdbook = "0.4.10"
regex = "*"
serde = "*"
serde_json = "*"
urlencoding = "2.0.0"
