[package]
name = "mdbook-wikilink"
version = "0.1.4"
authors = ["Leo Silva Souza <leovano@protonmail.com>"]
edition = "2018"

[dependencies]
clap = "*"
mdbook = "0.4.10"
regex = "*"
serde = "*"
serde_json = "*"
urlencoding = "2.0.0"
